server:
  port: 31010
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cmss
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtualHost: /
xuecheng:
  mq:
    #queue: queue_cms_postpage_01
    #routingKey: 5a751fab6abb5044e0d19ea1   #门户的站点
    queue: queue_cms_postpage_03
    routingKey: 5b30cba5f58b4411fc6cb1e5

